/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 23 10:16:17 GMT 2020
 */

package com.gildedrose;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.gildedrose.GildedRose;
import com.gildedrose.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class GildedRose_ESTest extends GildedRose_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Item[] itemArray0 = new Item[4];
      Item item0 = new Item("Backstage passes to a TAFKAL80ETC concert", (-25), 49);
      itemArray0[0] = item0;
      Item item1 = new Item("Backstage passes to a TAFKAL80ETC concert", 49, 49);
      itemArray0[1] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Item[] itemArray0 = new Item[4];
      Item item0 = new Item("t'/axNRq]lzitMqTi", 0, 50);
      itemArray0[0] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      item0.name = "Aged Brie";
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("", 1, 1);
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Item[] itemArray0 = new Item[11];
      Item item0 = new Item("L=EQ&S", 85, 85);
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      itemArray0[2] = item0;
      itemArray0[3] = item0;
      itemArray0[4] = item0;
      itemArray0[5] = item0;
      itemArray0[6] = item0;
      itemArray0[7] = item0;
      Item item1 = new Item("L=EQ&S", (-41), 85);
      itemArray0[8] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Item[] itemArray0 = new Item[4];
      Item item0 = new Item("Backstage passes to a TAFKAL80ETC concert", 0, 11);
      itemArray0[0] = item0;
      itemArray0[1] = itemArray0[0];
      Item item1 = new Item("Backstage passes to a TAFKAL80ETC concert", 11, 11);
      itemArray0[2] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Item[] itemArray0 = new Item[11];
      Item item0 = new Item("L=EQ&S", 85, 85);
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      itemArray0[2] = item0;
      itemArray0[3] = item0;
      Item item1 = new Item("Aged Brie", (-2327), (-41));
      itemArray0[4] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Item item0 = new Item("Sulfuras, Hand of Ragnaros", (-1168), 130);
      Item[] itemArray0 = new Item[7];
      itemArray0[0] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Item[] itemArray0 = new Item[11];
      Item item0 = new Item("Backstage passes to ` TAFKAL80ETC concert", (-1), (-1));
      itemArray0[0] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Item[] itemArray0 = new Item[3];
      Item item0 = new Item("Backstage passes to a TAFKAL80ETC3concert", 1745, 1745);
      itemArray0[0] = item0;
      Item item1 = new Item("Backstage passes to a TAFKAL80ETC concert", (-1962), 1745);
      itemArray0[1] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.updateQuality();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Item[] itemArray0 = new Item[1];
      Item item0 = new Item("Aged Brie", (-1218), 1068);
      itemArray0[0] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      gildedRose0.updateQuality();
  }
}
