/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 23 10:16:13 GMT 2020
 */

package com.gildedrose;

import org.junit.Test;
import static org.junit.Assert.*;
import com.gildedrose.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class Item_ESTest extends Item_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Item item0 = new Item("", 3653, 3598);
      String string0 = item0.toString();
      assertEquals(", 3653, 3598", string0);
  }
}
